# Generated by Django 6.0.5 on 2026-05-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("TRANSFER_SENT", "Transfer Sent"),
                    ("TRANSFER_RECEIVED", "Transfer Received"),
                ],
                max_length=20,
            ),
        ),
    ]
